"""add relationships

Revision ID: d860c902e90f
Revises: e4a5ae04271a
Create Date: 2025-12-19 19:57:20.166072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd860c902e90f'
down_revision: Union[str, Sequence[str], None] = 'e4a5ae04271a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_studios_id'), 'studios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studios_id'), table_name='studios')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    # ### end Alembic commands ###
