"""studios and booking

Revision ID: e4a5ae04271a
Revises: ad8bec412eb0
Create Date: 2025-12-19 18:08:08.037497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a5ae04271a'
down_revision: Union[str, Sequence[str], None] = 'ad8bec412eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.add_column('studios', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_studios_id'), table_name='studios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_studios_id'), 'studios', ['id'], unique=False)
    op.drop_column('studios', 'is_active')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
